### ISSUE TITLE
SLURM submission

### ISSUE THREAD

**Issue by wabdel** [AndrewWAlexander/MMCTP#11]
Hello Andrew

I am using slurm queueing system installed on 4 linux boxes. I had to modify in your code three instances for capital letters "SLURM" and change them to small letters "slurm" for the submission to work. It was an easy fix for me.

The problem I face now is the MMCTP can not submit to slurm if the shell machine is running all nodes with calculations. Is MMCTP detecting machine load and would generally not submit calculation request if it is at 100% usage?

**Comment by AndrewWAlexander** [comment]
Hi Wamied, 

I've updated the EGSnrc calls for slurm to use lower case letters. This can be found in the following commit. 
34d462d380780dcf175a8ed53171226c90f1c4b8

In terms of how MMCTP submit jobs, there is a limit per shell that prevents MMCTP from submitting additional jobs. The user sets this limit in the shell configurations.

A
