### ISSUE TITLE
MLC step & shoot + Sliding window

### ISSUE THREAD

**Issue by wabdel** [AndrewWAlexander/MMCTP#12]
MMCTP although writes an MLC file with correct Subfieldsn and dose indexes, I am having trouble. It does not submit correct MLC file format for beam calculation.

I am made a converter in xojo to read MMCTP MLC file and convert it to a BEAMnrc MLC format file.

[https://github.com/wabdel/DYNVMLC-converter.git](url) 

An example is attached (I changed to extensions to txt)
[BEAMnrc_MLC.txt](https://github.com/AndrewWAlexander/MMCTP/files/4931318/BEAMnrc_MLC.txt)
[MMCTP_MLC.txt](https://github.com/AndrewWAlexander/MMCTP/files/4931321/MMCTP_MLC.txt)

**Comment by wabdel** [comment]
Andrew. The problem might be due to macOS Catalina. I changed in App open so that the targets for local_endline are only two (Windows and Else). macOS by default uses EndOfLine.Unix. The EndOFLine.macos does not properly work.
#If TargetWindows Then
  
  local_endline=EndOfLine.Windows
  App.MDIWindow.Height=720
  App.MDIWindow.Width=1200
  
  If Screen(0)<>Nil Then
    
    App.MDIWindow.Top= Screen(0).height/2 - App.MDIWindow.height/2
    App.MDIWindow.Left = Screen(0).Width/2 - (App.MDIWindow.Width/2)
    
  End
  
#Else
  
  
  //removed mac and unix conditions. THey are redundent.
  //Wamied Abdel-Rahman 18 July 
  local_endline=EndOfLine.unix
  
#EndIf

**Comment by AndrewWAlexander** [comment]
Thanks for the comment Wamied. I believe you are now aware how MMCTP converts the DICOM MLC information into the MMCTP format and subsequent BEAMnrc format.

**Comment by wabdel** [comment]
Thank you Andrew. Everyday I get to learn something new about the code.
