### ISSUE TITLE
CT model

### ISSUE THREAD

**Issue by moralesjohnny** [AndrewWAlexander/MMCTP#3]
Hi Andrew,

just a query on the CT model. I am attaching an image showing a CT data sample. I am thinking on using 521icru as the PEGS data.

But for the materials which were used to get the HU values on the scanner (they have been circled in the picture), should they match the names in the 521icru file? or can be they be left as they are on my picture?

Thanks for your help.

![testct](https://cloud.githubusercontent.com/assets/22019301/18261680/45cc503a-743e-11e6-96a8-874fdca93195.png)

**Comment by AndrewWAlexander** [comment]
Hi Johnny,

The material names have to match the names within the pegs file. I would
assume that you will need to add 521ICRU after each of those names. To get
the exact wording, open up your pegs file and see how they are labeled
there.

Andrew
